### ISSUE TITLE
Style/MethodMissing: When using method_missing, define respond_to_missing? and fall back on super.

### ISSUE THREAD

**Issue by yurik763** [rubizza-camp/summer-2019#131]
Style/MethodMissing: When using method_missing, define respond_to_missing? and fall back on super.

_Originally posted by @hound in https://github.com/rubizza-camp/summer-2019/pull/85_

**Comment by anatoliliotych** [comment]
You can skip this, because you are playing with method missing test.

**Comment by yurik763** [comment]
Пишет: Some checks haven’t completed yet. 
Мой ментор сказал, что проверить не может, возможно вы мне назначите другого ментора для проверки?
